# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolveCpp <- function(a, b) {
    .Call(`_Mkt01_convolveCpp`, a, b)
}

modifyDataFrame <- function(df) {
    .Call(`_Mkt01_modifyDataFrame`, df)
}

DateExample <- function(dv, dtv) {
    .Call(`_Mkt01_DateExample`, dv, dtv)
}

timesTwo <- function(x) {
    .Call(`_Mkt01_timesTwo`, x)
}

makeDataFrame <- function(inX) {
    .Call(`_Mkt01_makeDataFrame`, inX)
}

FibCpp0 <- function(n) {
    .Call(`_Mkt01_FibCpp0`, n)
}

rcpp_hello_world <- function() {
    .Call(`_Mkt01_rcpp_hello_world`)
}

